### PR TITLE
HTML Reader: be more forgiving about figcaption

### LINKED ISSUE #4183: HTML Reader: Regression for figure without figcaption
HTML `figure`s without a corresponding `figcaption` should fall back to the `alt` text of the `img` (as was the behaviour prior to #3813) rather than having no caption at all.

```
$ pandoc -v
pandoc 2.0.5
$ echo '<figure><img src="foo" alt="bar"></figure>' | pandoc -f html -t markdown
![](foo)
$ echo '<img src="foo" alt="bar">' | pandoc -f html -t markdown
![bar](foo)
```

A related issue is that `figcaption` is ignored when it contains block tags like `div` or `p`:

```
$ echo '<figure><img src="foo" alt="bar"><figcaption><p>baz</p></figcaption></figure>' \
  | pandoc -f html -t markdown
![](foo)
$ echo '<figure><img src="foo" alt="bar"><figcaption><div>baz</div></figcaption></figure>' \
  | pandoc -f html -t markdown
![](foo)
$ echo '<figure><img src="foo" alt="bar"><figcaption><span>baz</span></figcaption></figure>' \
  | pandoc -f html -t markdown
![baz](foo)
```

### PR DESCRIPTION
**Pull request by mb21**
fixes #4183

### CODE REVIEW

**Comment by mb21** [comment]
update: got this working...

File: src/Text/Pandoc/Readers/HTML.hs [hunk 1]
```diff
@@ -588,17 +588,23 @@ pFigure = try $ do
   skipMany pBlank
   let pImg  = (\x -> (Just x, Nothing)) <$>
                (pOptInTag "p" pImage <* skipMany pBlank)
-      pCapt = (\x -> (Nothing, Just x)) <$>
-               (pInTags "figcaption" inline <* skipMany pBlank)
+      pCapt = (\x -> (Nothing, Just x)) <$> do
+                skipMany pBlank
+                bs <- pInTags "figcaption" block
+                skipMany pBlank
+                let getInlines (Plain xs) = xs
```
Comment (jgm) [inline src/Text/Pandoc/Readers/HTML.hs]: Couldn't we just use `blocksToInlines` from `Text.Pandoc.Shared`?

File: src/Text/Pandoc/Readers/HTML.hs [hunk 2]
```diff
@@ -588,17 +588,23 @@ pFigure = try $ do
...
   let mbimg = msum $ map fst res
   let mbcap = msum $ map snd res
   TagClose _ <- pSatisfy (matchTagClose "figure")
-  let caption = fromMaybe mempty mbcap
   case B.toList <$> mbimg of
-       Just [Image attr _ (url, tit)] ->
-         return $ B.para $ B.imageWith attr url ("fig:" ++ tit) caption
+       Just [Image attr alt (url, tit)] ->
+         let caption = fromMaybe alt mbcap
+         in  return $ B.para $ B.imageWith attr url ("fig:" ++ tit) $ B.fromList caption
```
Comment (jgm) [inline src/Text/Pandoc/Readers/HTML.hs]: As noted in the linked issue, I'm not convinced we should do this.  The HTML doesn't have a caption, so why should we produce an image with a caption?  The tricky thing is that we're overloading `alt`; it will still be used for the image's alt text, which just disappears in the current setup.  I'm not for the alt attribute disappearing, but I'm also hesitant about creating a caption where there wasn't one before.

**Comment by mb21** [comment]
Thanks for the feedback, I agree.

One thing: `Text.Pandoc.Shared` should also export `blocksToInlines'`, don't you think? The two places where `blocksToInlines` is already used, `fromList` is immediately called on it. Should I make another pull for that?

**Comment by jgm** [comment]
+++ Mauro Bieg [Dec 22 17 11:23 ]:
>   Thanks for the feedback, I agree.
>
>   One thing: Text.Pandoc.Shared should also export blocksToInlines',
>   don't you think? The two places where blocksToInlines is already used,
>   fromList is immediately called on it. Should I make another pull for
>   that?

Sure.

**Comment by mb21** [comment]
btw, I've rebased this and changed according to your comments.

File: src/Text/Pandoc/Readers/HTML.hs [hunk 3]
```diff
@@ -588,8 +588,11 @@ pFigure = try $ do
   skipMany pBlank
   let pImg  = (\x -> (Just x, Nothing)) <$>
                (pOptInTag "p" pImage <* skipMany pBlank)
-      pCapt = (\x -> (Nothing, Just x)) <$>
-               (pInTags "figcaption" inline <* skipMany pBlank)
+      pCapt = (\x -> (Nothing, Just x)) <$> do
```
Comment (jgm) [inline src/Text/Pandoc/Readers/HTML.hs]: You probably want to put a try around this one.
Otherwise it may fail after consuming some blanks, if there's no figcaption.

Comment (jgm) [reply src/Text/Pandoc/Readers/HTML.hs]: `try (skipMany pBlank *> pInTags "figcaption" inline <* skipMany pBlank)`

Comment (jgm) [reply src/Text/Pandoc/Readers/HTML.hs]: Actually, do you need the `skipMany pBlank`?  Won't this be handled by `pSkip`?

**Comment by mb21** [comment]
right... thanks!
